### ISSUE TITLE
When try to use _restart

### ISSUE THREAD

**Issue by TR1D** [TortoiseOrHare/NoCheatZ-4#174]
Dedicated csgo server, steam, no mods
NoCheatZ v4 r16, debian

!stacktrace.txt:
```/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0x100bd8)[0xae0c8bd8]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0x100e21)[0xae0c8e21]
linux-gate.so.1(__kernel_sigreturn+0x0)[0xb7752d1c]
/home/steam/cs_awp/bin/libstdc++.so.6(_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc+0x38)[0xb6eeabe0]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0x1262e3)[0xae0ee2e3]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0x12684c)[0xae0ee84c]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0xf4bd1)[0xae0bcbd1]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0xf51bd)[0xae0bd1bd]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0xf4891)[0xae0bc891]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0xf3ff1)[0xae0bbff1]
/home/steam/cs_awp/csgo/addons/NoCheatZ/nocheatzX.so(+0x120842)[0xae0e8842]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x31181)[0xb7565181]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x311dd)[0xb75651dd]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xfb)[0xb754da6b]
./srcds_linux[0x80488bd]
Caught signal 11 (SIGSEGV)
```

**Comment by L-EARN** [comment]
Hi,

Is it really necessary for you to use this command ?

**Comment by TR1D** [comment]
No, just for information.

**Comment by L-EARN** [comment]
I was already aware of this issue.

It's a different part of the issue I was aware ... but it's not a priority for me.

If the server crash when the plugin unloads (when we quit), it's not a big deal I think.

I already though about a solution to prevent this. But it would prevent me from doing something else because soon I will not have enough time to work on prior things.

Thank you TR1D.

This stays open though.

**Comment by diman1000w** [comment]
В NoCheatz 4 r30 сервер падает при смене карты.

**Comment by diman1000w** [comment]
v4-r45 так же сервер падает при смене карты. Сервер под  Windows стоит.

**Comment by L-EARN** [comment]
@diman1000w Hi, please create a new detailed issue here : https://github.com/L-EARN/NoCheatZ-4/issues/new

**Comment by TR1D** [comment]
Problems starts when you use the autoupdate plugin https://forums.alliedmods.net/showthread.php?p=2238058
Which in turn uses _restart
