### ISSUE TITLE
 Test NoCheatZ-4 on the server under Windows.

### ISSUE THREAD

**Issue by diman1000w** [TortoiseOrHare/NoCheatZ-4#182]
Сигнатура проблемы:
  Имя события проблемы:	BEX
  Имя приложения:	srcds.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	595ecaf0
  Имя модуля с ошибкой:	nocheatzX.dll
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	597a84b8
  Смещение исключения:	000e2ca9
  Код исключения:	c0000417
  Данные исключения:	00000000
  Версия ОС:	6.1.7601.2.1.0.768.3
  Код языка:	1049
  Дополнительные сведения 1:	6c5e
  Дополнительные сведения 2:	6c5e3960c6f03ed468d6c9ca2aa8c351
  Дополнительные сведения 3:	acbb
  Дополнительные сведения 4:	acbbaecfd94de5a8d21c5ceb8a40d0fb

**Comment by diman1000w** [comment]
Сервер под Windows. На сервере mmsource-1.10.7-git959-windows; sourcemod-1.8.0-git6015-windows

**Comment by T1MOXA** [comment]
Я не думаю что автор понимает русский, так что чтоб все вас поняли переоформите на английском языке.

**Comment by diman1000w** [comment]
В этой версии v4-r56: Merge pull request #189 from L-EARN/dev2 сервер падает но редко.

**Comment by diman1000w** [comment]
Имя события проблемы:	BEX
  Имя приложения:	srcds.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	595ecaf0
  Имя модуля с ошибкой:	nocheatzX.dll
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	597c9100
  Смещение исключения:	000e2489
  Код исключения:	c0000417
  Данные исключения:	00000000
  Версия ОС:	6.1.7601.2.1.0.768.3
  Код языка:	1049
  Дополнительные сведения 1:	6c5e
  Дополнительные сведения 2:	6c5e3960c6f03ed468d6c9ca2aa8c351
  Дополнительные сведения 3:	5fbf
  Дополнительные сведения 4:	5fbfaa192dc059aed4f0386d5295b672

**Comment by L-EARN** [comment]
Hi,

You seems to break in the standard C function "localtime".
I have no idea why. Maybe a I18n issue ...

Do you have something in `csgo/addons/NoCheatZ/!stacktrace.txt` ?

**Comment by diman1000w** [comment]
!stacktrace не появляется. Раньше появлялось но там пусто было.

**Comment by L-EARN** [comment]
Can you test running your operating system and your game server in english ?

**Comment by diman1000w** [comment]
Well the server for 2 hours has never fallen with this version I will observe further.
V4-r58: запрос слияния с вытягиванием # 192 из L-EARN / dev2

**Comment by diman1000w** [comment]
[Desktop.zip](https://github.com/L-EARN/NoCheatZ-4/files/1186067/Desktop.zip)

Look, please, there may be false bans and many messages in the chat.

**Comment by L-EARN** [comment]
Hi,

Can I have fy_snow-strike-07-30-17_23-30-08.dem please ? (BATMAN + hloij B3nya)

I choose this demo randomly.

**Comment by diman1000w** [comment]
[!stacktrace.zip](https://github.com/L-EARN/NoCheatZ-4/files/1187307/stacktrace.zip)
Drops the server looks can something to fix it.

**Comment by diman1000w** [comment]
[NoCheatZ-31-Jul-2017.zip](https://github.com/L-EARN/NoCheatZ-4/files/1187324/NoCheatZ-31-Jul-2017.zip)

**Comment by diman1000w** [comment]
NoCheatZ v4-r65
[!stacktrace.zip](https://github.com/TortoiseOrHare/NoCheatZ-4/files/1197207/stacktrace.zip)
[NoCheatZ-03-Aug-2017.zip](https://github.com/TortoiseOrHare/NoCheatZ-4/files/1197211/NoCheatZ-03-Aug-2017.zip)

**Comment by L-EARN** [comment]
Hi,

I code the project using visual studio and test on windows.

I can't replicate this bug. In fact it doesn't seems to crash inside nocheatz plugin. But I assume nocheatz is doing an indirect error causing a later crash.

There is not enough information yet for me to even try to fix this. Sorry.

Could you identify a conflicting plugin ?

**Comment by diman1000w** [comment]
Wash due to this plugin started Custom_Rounds and modules to it.

**Comment by diman1000w** [comment]
Server crashes in this version of NoCheatZ v4-r67

**Comment by diman1000w** [comment]
NoCheatZ v4 r75
[!stacktrace.zip](https://github.com/TortoiseOrHare/NoCheatZ-4/files/1232862/stacktrace.zip)

**Comment by L-EARN** [comment]
I have no control over this issue. You seems to be the only one responsible of this.
