### ISSUE TITLE
[QUESTION] WCS MOD | Speed, Aim, LongJump and other

### ISSUE THREAD

**Issue by BlackYuzia** [TortoiseOrHare/NoCheatZ-4#190]
Game: CS:GO
OC: Linux
Mod: SM,MM, War3Craft (WC:SOURCE)

@L-EARN I have a one question.
I have a servers with WCS mod. And I do not know HOW your AC (AntiCheat) reacts to this mod.
That mod have not normal speed, teleports and other. And AC can say: That Speedhack, That Cheat or other.
and That mod have: Speed skills, Dmg skills, Vampire skills, LongJump Skills, Teleport Skills, Fly Skills, no damage (I mean: Fall damage, no body/head dmg and others) AIM skills (yes, AIM-BOT SKILL) WH SKILLS and others.
That not (big) problem for that AC? Or I most Customized AC for MOD WCS And he's friends?

If you not know what a mod WCS, you can connect to my server and check mod:
IP: 37.230.210.50:27015
Retry: Game CS:GO

Oh, and other mods will be support AC?
I mean: Zombie Plugin (ZP), Zombie Reload (ZR), Surf, (DeathRun, JailBreak (JB) - I'm not sure what to use. But it will not hurt to ask)

Sry if so many topics.

**Comment by L-EARN** [comment]
Hi,

Just run the plugin with kick/ban disabled and log set to admins. Let me know how it turns out.

But I don't think there is a real purpose to setup an anticheat on a server that is allowing cheats ...

**Comment by BlackYuzia** [comment]
no-no, @L-EARN 
There's have cheats (aim-wh) but they are used very rarely. 

Okey, I add AC to server and disabled ban/kick.

 

> But I don't think there is a real purpose to setup an anticheat on a server that is allowing cheats

In fashion, though, there are skills and stuff.
BUT cheaters (which for example spin, or play with aim, WH, etc.) severely interfere with NOT pumped players and others.

And have one quest.
How much is the server loaded?
What does the load depend on?

Since it is not very important in Public.
There are no "powerful" mods.
And the WCS itself is "big" and there's another AC

**Comment by L-EARN** [comment]
If you mean performance : 
On a windows server playing de_inferno, with1 human and 9 bots on a classical bomb game using r49.
NoCheatZ takes **0,68 % of exclusive time** / **7,21 % of inclusive time**.
Exclusive means it only counts the code inside the module. Inclusive means it also count the calls made by nocheatz inside other modules (hooks).
Inside the 0,68 %, **the WallhackBlocker is the most expensive** with almost 0,30% of exclusive time, almost 4% of inclusive time. So the WallhackBlocker takes himself 50% of NoCheatZ performance.

As a comparison, if we add all the MM/SM modules, **SourceMod takes 4,2% of exclusive time**.

![perfr49](https://user-images.githubusercontent.com/13771307/28746422-5bdae40a-748c-11e7-9793-46703fde6e3f.png)

**Comment by BlackYuzia** [comment]
@L-EARN thanks for info.
But, I use LINUX system, and in server play 10+ players (no bots)
How I can know how match system load?
In linux OS.

Oh, and sv in my server has been red (up) >20+
Lags and Freezes D:
I watch and see:
When any player get ban, server sv has been red in 100+

**Comment by L-EARN** [comment]
You should try to disable wallhackblocker.

**Comment by BlackYuzia** [comment]
@L-EARN yea, that help.
Thanks.

lol, WH not block, but CPU eated, WHY he enabled? :d

**Comment by L-EARN** [comment]
Set `ncz BanRequest AllowWriteBans No` if you don't want the plugin to write bans in banned_id.cfg or banned_ip.cfg.

**Comment by BlackYuzia** [comment]
@L-EARN here is new problem :d
Problem: AllowWriteBans - not work?
`ncz BanRequest AllowWriteBans No`
 but bans write in banned_id.cfg AND banned_ip.cfg

Where I reload cfg:
(exec .cfg)
```
         action AllowWriteBans not found.
         Try : Verbose - CanKick - CanBan - AllowWriteBans
```
Screens:

![3](https://user-images.githubusercontent.com/25010528/28752938-6f560dfa-7533-11e7-80ec-d404dee3e8d3.png)
![2](https://user-images.githubusercontent.com/25010528/28752937-6f5550f4-7533-11e7-8bf0-dd72415b07e7.png)
Sry, I very love (Vectors/Arrows/Pointers) :d
![5](https://user-images.githubusercontent.com/25010528/28752944-7a26c3be-7533-11e7-8058-e77fcc5a048c.png)
