### ISSUE TITLE
[REQ] DM FFA WALLHACK 

### ISSUE THREAD

**Issue by warlock396** [TortoiseOrHare/NoCheatZ-4#199]
CSGO

r61. Win7 x64

Deathmatch FFA

Dedicated

LAN, No-Steam

Request - Please, add feature to hide on wallhack blocker teammates, because on DM FFA i can see enemies, witch in my team, so, teammates_are_enemies 1, like this. And cheater have to see 50% of players throw the walls

**Comment by warlock396** [comment]
Also, request to modify demo recorder, to start record demo when on server at least 1 player, and dont record demos when on server 0 players

**Comment by L-EARN** [comment]
I tried implement wallhackblocker for teammates. But I don't know why it won't work. So I abort this.

**Comment by L-EARN** [comment]
I'll try again soon. I must try without testing bAlways value.
