### ISSUE TITLE
[REQUEST] Silent AIM (no visible aim)

### ISSUE THREAD

**Issue by BlackYuzia** [TortoiseOrHare/NoCheatZ-4#214]
Hello, 
Now I tested anything type AIM and other.
I find type aim what NCZ not see and can't detect. (maybe)
That type: (use google If you do not know what the aim)

> **SILENT AIM** 

FOV < 5
SPEED = 1.0

> That cheats was Crack (I mean that was crack Private)

 I find thim when I tested other cheats
If you need, I can give you that crack. (I use that hack only in **NO-STEAM**)
**I play 1 hour and I do not get BAN.**

> I think, That  AIM do not detect without SILENT too, But I do not test that.

**Comment by L-EARN** [comment]
Hi,

I will try to implement this detection.
It seems to be easy to do.

Better give this a try than doing nothing.

Thank you.

**Comment by BlackYuzia** [comment]
```
Better give this a try than doing nothing.
```
Does this mean you give me this (private cheat crack) or is it just a saying?
If that yes:
[[CHEAT].zip](https://github.com/TortoiseOrHare/NoCheatZ-4/files/1198215/CHEAT.zip)
If no - I deleted that *.zip*

**Comment by L-EARN** [comment]
This is now partially fixed by the game and will help incoming detections.
