### ISSUE TITLE
[BUG?] Speed Hack Detected [CS:GOvno]

### ISSUE THREAD

**Issue by BlackYuzia** [TortoiseOrHare/NoCheatZ-4#216]
> Game: CS:GO
> OS: LINUX
> R65

I see ban:
That normal ban or not?
How player can use SPEED HACK in server (CS:GO)
> 08/03/17 20:29:33 [ Server Tick #80175] Администратор STEAM_1:0:1602194185 : SpeedHack detected
> 08/03/17 20:29:33 [ Server Tick #80175] v4-r65-0-ga1ad598
> 08/03/17 20:29:33 [ Server Tick #80175] :::: SpeedHolderT {
> :::::::: Ticks Left : 0.000000,
> :::::::: Detections Count : 30,
> :::::::: Last Detection Time 26074.229887,
> :::::::: Last Latency : 0.076348,
> :::::::: Last Test Time : 26074.213993
> :::: }
> 08/03/17 20:29:43 [ Server Tick #80817] Player disconnect : Администратор [STEAM_1:0:1602194185] -> Reason : Забанен админом: Server
> Причина: "Banned by NoCheatZ 4 : SpeedHack"
> Бан выдан: 08/03/2017 - 20:29:43
> Забанен на: 2 hours

**Comment by warlock396** [comment]
There is no SpeedHack cheats for csgo,
maybe it causing by lag from player (high ping), OR teleport hack.
Also maybe Airstuck collision.

**Comment by BlackYuzia** [comment]
You think I most disabled func? 
I think that do not need.

**Comment by SM91337** [comment]
The speedhack module should be disabled on CSGO, it was already patched a long time ago.

**Comment by warlock396** [comment]
Yes, i think it's false positive.
Better way - disable this module.
