### ISSUE TITLE
Process all clients optionally and clone visibility for spectators

### ISSUE THREAD

**Issue by SM91337** [TortoiseOrHare/NoCheatZ-4#218]
**Process all clients optionally**
Check PVS on team mates as well as enemies optionally, this could be useful for game modes where its Free For All, such as Deathmatch servers, It will be very expensive but I feel it should be an option regardless.

**Clone visibility for spectators**
If you are spectating somebody, what you see should clone client being spectated, this is useful for admin esp plugins so we can get a true idea of what the player sees.

**Comment by L-EARN** [comment]
Fixed in r68.

I could use mp_teammates_are_enemies convar but I don't know why I forgot about it when coding.
So you need to use `ncz wallhackblocker setffamode`.

ref #199 @warlock396
