### ISSUE TITLE
WH Blocker may work better...

### ISSUE THREAD

**Issue by warlock396** [TortoiseOrHare/NoCheatZ-4#219]
r67 
csgo dedicated server
win7 x64
dm (but its nevermind)
![de_dust20005](https://user-images.githubusercontent.com/22426736/28980576-05fa2c10-7957-11e7-9dff-e9fbd4a6c1c8.jpg)
![de_dust20006](https://user-images.githubusercontent.com/22426736/28980577-05fe7a86-7957-11e7-9fe1-82cb1eaa0c15.jpg)
![de_dust20007](https://user-images.githubusercontent.com/22426736/28980579-06058a6a-7957-11e7-9646-d98c73680494.jpg)
![de_dust20004](https://user-images.githubusercontent.com/22426736/28980578-06033026-7957-11e7-9864-6deff70e875e.jpg)

**Comment by BlackYuzia** [comment]
When I enable that func in my server.
That not work. Players visible in all maps.

**Comment by BlackYuzia** [comment]
In my server included plugin *ADMIN ESP*
That can be a problem this?

**Comment by warlock396** [comment]
Выключить да проверь)

**Comment by hooliganxxx** [comment]
Админ есп полезная штука. Единственное, я думаю можно найти способ использовать стандартные/встроенные приколы ксго для реализации этой фишки - тогда проблем с античитом не будет. Я до сих пор не ставил еспшки, но мне нужно. Поэтому вопрос - кто какими пользуется?

**Comment by warlock396** [comment]
winx esp, ezfrags, Abitsmarter
Бесплатные.

П.С ну на тест античита то можно было и отключить admin esp :)

**Comment by hooliganxxx** [comment]
Ты уверен что мы говорим про серверные плагины есп?

**Comment by warlock396** [comment]
Я хз зачем ты вообще тогда тут обсуждаешь это, если это не имеет к данной ситуации никакого отношения. Тут как бы читы обсуждают в данный момент, а не твои серверные плагины.

**Comment by L-EARN** [comment]
Fixed in r68. Thanks for stopping bickering here on stuff that has nothing to do with the issue.
