### ISSUE TITLE
entity blocker issues

### ISSUE THREAD

**Issue by hooliganxxx** [TortoiseOrHare/NoCheatZ-4#223]
I uploaded the video so you could see how entities are not transmitted even being in front of each other.
This issue wasnt there before the latest update to r71...

Uploaded to rghost cause even with 20 seconds video is too big for gihub

`http://rgho.st/private/8wSzNvd96/d5342f8c63f21af15d4f9dbf5f8756ab`

It is not only me, but all players experencing the problem.

PS. I downgraded to r65 - the problem disappeared

**Comment by L-EARN** [comment]
https://github.com/TortoiseOrHare/NoCheatZ-4/releases/tag/v4-r73

**Comment by L-EARN** [comment]
https://github.com/TortoiseOrHare/NoCheatZ-4/releases/tag/v4-r75
