### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by MrMaZa1** [TortoiseOrHare/NoCheatZ-4#224]
Hello! On my server with your anti-cheat began to disappear the players when they run they are in 1-2-3 seconds Staude invisible

**Comment by L-EARN** [comment]
https://github.com/TortoiseOrHare/NoCheatZ-4/releases/tag/v4-r73

**Comment by MrMaZa1** [comment]
Now when I jump the players become invisible

**Comment by BlackYuzia** [comment]
lol, that fail :d

**Comment by L-EARN** [comment]
Yes I noticed that.

**Comment by L-EARN** [comment]
Test that please : https://github.com/TortoiseOrHare/NoCheatZ-4/releases/tag/v4-r75

**Comment by neatek** [comment]
No. players dissaper...
its annoying. 
its WallhackBlocker?

**Comment by MrMaZa1** [comment]
I have everything works fine,the models are not lost,well. THANKS
