### ISSUE TITLE
[suggestion] Screenshot's from player client-side

### ISSUE THREAD

**Issue by warlock396** [TortoiseOrHare/NoCheatZ-4#233]
Hello, i know, what only clientside anticheats (or not?) can receive informations like what happend on player's side, but, your AC is not a plugin, is there any variants to make functions, like receive screenshots from all players by admin-command, or automaticly in interval like 5 mins? This is very important part, bcz it can easy say for admin, truely player is cheater (wh/esp/bones/3Dmodel/champs/etc), or not.
I know another AC's - PunkBuster (not for Source Engine, but anyway), and UCP - they can do this, but they are clientside, not serverside.

Anyway i want to ask - can you make this feature? or this is impossible?
Maybe need to create new extension for server, i don't know, but there is no serverside AC, what can do this, but chance is always a chance :)

**Comment by BlackYuzia** [comment]
Yes, that will be great func. If that possible...

**Comment by BlackYuzia** [comment]
But. I have a one warn. If cheat will be great, or cheat run external type. If you use screenshot command. Screens will be clear.

**Comment by L-EARN** [comment]
That is not possible unless we force the client to install a binary file.
But we can't transmit a binary file.

**Comment by warlock396** [comment]
So, anyway, if i have a chance to force clients to install this file, can you do this? Like for me - i have my server, where all players play from my client (we have small city w/o internet and play on LAN, and i give them my client to play on my server).
But anyway i think there is must be solution for solve this problem.
Like in cs 1.6 with them AC's. If player dont have this binary - AC kick him, bcz he is not confirmed player for AC (i dont remember, but i think this AC is myAC were).
Your AC have Cvars checker, i think it can check, have player this binary, or not. And Admin can link to this binary in Motd, where players can copypaste it and install, and play.
There is great suggestion on my opinion, and only you can do this, please :(

**Comment by hooliganxxx** [comment]
wayLANder3 for your purposes its better to use client-server anticheats like EAC for example.
