### ISSUE TITLE
Auto Attack Tester false positive

### ISSUE THREAD

**Issue by SM91337** [TortoiseOrHare/NoCheatZ-4#234]
### The name of the game your server is running on and the version of the game.
CSGO

### The version of the plugin release (R) (Otherwise, link to commit/pull request/fork). If using a custom build, please list your compiler version, your server and builder OS versions.
v4 r75

### Are you using other mods (list please) ?
Sourcemod
Metamod

### Are you using a listen server or a dedicated server ?
Dedicated

### Is the server localhost, LAN or remote ? Using Steam ? (A connect-link to a test-server is allowed)
No

### Expected behavior ?
No false positive

### Current behavior ? (You can link a demo/video and logfiles. Don't forget to strip personnal and sensitive informations before.)
False positive

### Steps to reproduce the problem ?
bind mwheeldown "+attack" Then scroll as fast as you can.

**Comment by SM91337** [comment]
Unfortunately it seems like its impossible to fix this false detection unless we can make sure the player does not use any crazy binds like scroll wheel...

**Comment by warlock396** [comment]
If this is spam - just kick player with cvar spam (+attack and etc, like connect spam), imho
