### ISSUE TITLE
Steam new release 18.08.2017 not compatible with NCZ

### ISSUE THREAD

**Issue by hooliganxxx** [TortoiseOrHare/NoCheatZ-4#242]
Hi, I updated my server to the latest steam release.
NCZ is not compatible. 
Crashes on player connect. And restarts automatically.
Tried r65 and r75. Without ncz works just fine.
Please update :)

**Comment by wayLANder3** [comment]
Same

**Comment by Weeeishy** [comment]
Here aswell. No crashes after I renamed the nocheatz folder.

**Comment by wayLANder3** [comment]
Seem's like it's not NCZ problem. Update sourcemod, there's some new build's update's today for fixing crashes.

**Comment by Weeeishy** [comment]
Yeah I'm aware of that. But still, some stuff changed like signatures. I don't know whats excatly the issue, but even with the newest gamedata of sourcemode, it's still crashing with ncz

**Comment by L-EARN** [comment]
Hi,

In CSGO block of config.ini, replace : 

```
playerruncommand_windows=470
playerruncommand_linux=471
```

That is enough.

Be aware sourcemod is not yet fully fixed.

**Comment by Weeeishy** [comment]
Thank you! The server seems stable now

**Comment by Dreizehnt** [comment]
Doesn`t work for me... SM 1.9.0.6138...

**Comment by hooliganxxx** [comment]
Nice, thank you, @L-EARN :)
