### ISSUE TITLE
Player model stays invisible for a millisecond after peeking them

### ISSUE THREAD

**Issue by Weeeishy** [TortoiseOrHare/NoCheatZ-4#247]
You're not forced to complete all the followings, but any detail can help.

### The name of the game your server is running on and the version of the game.
CSGO, latest version

### The version of the plugin release (R) (Otherwise, link to commit/pull request/fork). If using a custom build, please list your compiler version, your server and builder OS versions.

Latest stable release.

### Are you using other mods (list please) ?

 SourceMod Version: 1.8.0.5998
Metamod:Source version 1.10.7-dev

### Are you using a listen server or a dedicated server ?
Dedicated server

### Is the server localhost, LAN or remote ? Using Steam ? (A connect-link to a test-server is allowed)

Steam

### Expected behavior ?

Player model to always show up without staying invs.

### Current behavior ? (You can link a demo/video and logfiles. Don't forget to strip personnal and sensitive informations before.)

https://www.youtube.com/watch?v=7TA29EEshxU (Sorry for the bad quality)

### Steps to reproduce the problem ?

Thank you.

**Comment by wayLANder3** [comment]
same here
https://github.com/TortoiseOrHare/NoCheatZ-4/issues/237

**Comment by Weeeishy** [comment]
Ops my bad. I will close this one then.. 


Sorry
