### ISSUE TITLE
Dev hold - unhold

### ISSUE THREAD

**Issue by L-EARN** [TortoiseOrHare/NoCheatZ-4#248]
Hi,

I'm announcing there will be no development anymore, from myself, concerning this project. This, for an undetermined amount of time ... again.

I agree with you if you think I make a mistake regarding the way I manage all of that.
However I think this project evolved in the wrong way.

I'm currently trying to understand deep-learning using https://github.com/tensorflow/tensorflow as I'd love to implement this for ncz (But there is not enough information about how to use it in 3D environments instead of pictures) and I'm also taking care of other personnal projects.

This is not an apologize. I could die tomorrow in a accident or whatever else ; I prefer to optimize the way I use my time rather than urge fixing for issues, in a project that is not answering needs while thinking for a greater model for ncz.

Open issues checkpoint : 
#246 
#245 
#244 
#243 
#241 
#240 
#238 
#237 
#236 
#235 
#232 
#231 
#230 
#229 
#228 
#227 
#217 
#214 
#211 
#201 
#194 
#191 
#182 
#167

**Comment by hooliganxxx** [comment]
It's your choice and life, man. Good luck. 
Thanks for good work. 
We will miss you.

**Comment by L-EARN** [comment]
Enough for my own drama.

This time I aplogize. I made the wrong decision.
I will _try to_ fix the most issues as I can and let he project walk to the top before ever thinking of goals I can't even achieve.

However I still dedicate a lot less time to this project.

I'm always open to pull-requests, able to give advices for the guys who would like to contribute.
You can add me on steam for that reason ... or if you want to complain, cry, learn, help, encourage ... whatever ... as long as you know english or french => http://steamcommunity.com/id/wdtjfj

**Comment by BlackYuzia** [comment]
@L-EARN  Comeback is Real? :d

**Comment by Weeeishy** [comment]
Awesome to see you back again. No need to apologize, you do what you see is necessary. We do appreciate this amazing project and your efforts, as it helped many communities and servers.

Thank you

**Comment by wayLANder3** [comment]
Glad to see you, L-EARN, we believe in you, and in your work. 
And ofc we believe what your work is being better with every update :)
